package global

const (
	ID = "id"

	REFERENCES_EMAIL              = 1
	REFERENCES_MOBILE             = 2
	REFERENCES_RESIDENTIALADDRESS = 3
	REFERENCES_WEBSITEADDRESS     = 4
	REFERENCES_SOCIALADDRESS      = 5
	REFERENCES_FACEBOOK           = 6
	REFERENCES_LINKEDIN           = 7
	REFERENCES_GITHUB             = 8
	REFERENCES_INSTAGRAM          = 9
	REFERENCES_WHATSAPP           = 10
	REFERENCES_LANDLINE           = 11
	REFERENCES_ANONYMOUS          = 12
	REFERENCES_USER               = 13
	REFERENCES_CLIENT             = 14
	REFERENCES_TENANT             = 15
	REFERENCES_SUBCONTRACTOR      = 16
	REFERENCES_PARTNER            = 17
	REFERENCES_INCIDENT           = 18
	REFERENCES_COMPLAINT          = 19
	REFERENCES_ENQUIRY            = 20
	REFERENCES_SUGGESTION         = 21
)
